image: docker:latest
stages:
  - test
  - build

build_image:
  stage: build
  only:
    - main
  environment :
   name : itg
  script:
    - echo "Building the docker image ..."
    - echo "Tagging the docker image"
    - echo "Test Pipelien on minikube "

sonarqube-check:
  stage: test
  environment:
    name: recette
  image:
    name: sonarsource/sonar-scanner-cli:latest
    entrypoint: [""]
  variables:
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"
    GIT_DEPTH: "0"
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script:
    - sonar-scanner -X -Dsonar.host.url=http://192.168.56.1:9000
  rules:
    - if: $CI_PIPELINE_SOURCE=="merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME=="main"
    - if: $CI_COMMIT_REF_NAME == "main"
      when: never

