apiVersion: v1
kind: Service
metadata:
  name: front-service
  namespace: test
spec:
  selector:
    app: test-front
  type: NodePort
  ports:
  - name: frontend
    protocol: TCP
    port: 8081
    targetPort: 3000
    nodePort: 30003
  
---
apiVersion: v1
kind: Service
metadata:
  name: back-service
  namespace: test
spec:
  selector:
    app: test-back
  type: NodePort
  ports:
  - name: backend
    protocol: TCP
    port: 8001
    targetPort: 8000
    nodePort: 30004

---
apiVersion: v1
kind: Service
metadata:
  name: gitlab-service
  namespace: test
spec:
  selector:
    app: gitlab-runner
  type: NodePort
  ports:
  - name: gitlab-runner
    protocol: TCP
    port: 1472
    targetPort: 7000
    nodePort: 30005
---
apiVersion: v1
kind: Service
metadata:
  name: sonarqube-service
  namespace: test
spec:
  selector:
    app: test-local
  type: NodePort
  ports:
  - name: gitlab-runner
    protocol: TCP
    port: 1475
    targetPort: 9000
    nodePort: 30007

